# Generated by Django 4.2.11 on 2024-04-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="registration_no",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="user_profile",
            name="registration_no",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
