# Generated by Django 4.2.11 on 2024-04-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="equipment",
            old_name="cpu",
            new_name="CPU",
        ),
        migrations.RenameField(
            model_name="equipment",
            old_name="gpu",
            new_name="GPU",
        ),
        migrations.RenameField(
            model_name="equipment",
            old_name="ram",
            new_name="RAM",
        ),
        migrations.AlterField(
            model_name="equipment",
            name="equipment_image",
            field=models.ImageField(
                default="https://storage.googleapis.com/proudcity/mebanenc/uploads/2021/03/placeholder-image.png",
                upload_to="equipment_images/",
            ),
        ),
    ]
