# Generated by Django 4.2.11 on 2024-04-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "inventory",
            "0002_rename_cpu_equipment_cpu_rename_gpu_equipment_gpu_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="CPU",
            field=models.CharField(default="N/A", max_length=30),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="GPU",
            field=models.CharField(default="N/A", max_length=30),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="RAM",
            field=models.CharField(default="N/A", max_length=30),
        ),
    ]
