# Generated by Django 4.2.11 on 2024-04-21 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_alter_equipment_cpu_alter_equipment_gpu_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="equipment",
        ),
        migrations.AddField(
            model_name="reservation",
            name="equipment_type",
            field=models.CharField(
                choices=[
                    ("Equipment", "Equipment"),
                    ("MainEquipment", "MainEquipment"),
                ],
                default="N/A",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="MainEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_name", models.CharField(max_length=100)),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("audit", models.DateField(default=False)),
                ("location", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Available", "Available"),
                            ("In Use", "In Use"),
                            ("Under Maintenance", "Under Maintenance"),
                            ("Out of Service", "Out of Service"),
                        ],
                        default="Available",
                        max_length=20,
                    ),
                ),
                (
                    "device_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="main_equipments",
                        to="inventory.equipmenttype",
                    ),
                ),
            ],
        ),
    ]
