# Generated by Django 4.2.11 on 2024-04-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_remove_reservation_equipment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="equipment_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
