# Generated by Django 4.2.11 on 2024-04-21 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_reservation_equipment_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="equipment_id",
        ),
        migrations.AddField(
            model_name="reservation",
            name="equipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.equipment",
            ),
        ),
    ]
