# Generated by Django 4.2.11 on 2024-04-21 16:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_remove_reservation_equipment_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mainequipment",
            old_name="device_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="mainequipment",
            old_name="device_type",
            new_name="type",
        ),
    ]
