# Generated by Django 4.2.11 on 2024-04-21 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("inventory", "0007_rename_device_name_mainequipment_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipment",
            name="equipment_image",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="equipment",
        ),
        migrations.AddField(
            model_name="reservation",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
