# Generated by Django 4.2.11 on 2024-04-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0008_remove_equipment_equipment_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipment",
            name="return_date",
        ),
        migrations.AddField(
            model_name="reservation",
            name="return_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
