# Generated by Django 4.2.11 on 2024-04-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0009_remove_equipment_return_date_reservation_return_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="return_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
